### ISSUE TITLE
404 File Not Found - Thread for misguided links post migration

### ISSUE THREAD

**Issue by TheBlackxRanger** [emperorshammer/issues-incoming-queue#101]
#1 https://tc.emperorshammer.org/oob.php

Link listed on page https://tc.emperorshammer.org/tcunits.php under Complete List of Units

(old redirect is https://www.emperorshammer.org/oob.php )

**Comment by TheBlackxRanger** [comment]
2. On the About Page https://tc.emperorshammer.org/aboutus.php 

The Link to the TIE Corps points to https://tc.emperorshammer.rog/  
![image](https://user-images.githubusercontent.com/74426625/169078627-f55ce995-cc2f-4f03-9197-00d8e5609ba9.png)

**Comment by turtlexiv** [comment]
1 and 2 fixed (pending production push).
