### ISSUE TITLE
New Button Request

### ISSUE THREAD

**Issue by MarentaJean** [emperorshammer/issues-incoming-queue#106]
When you cancel a PvP or PvE Match Report, you are only given two options: "Return to Management" and "Submit another PvX Match Report".

Would be nice to have a 3rd option to "Return to View MP PvX Match Reports" so that you don't have to go back and forth through the options if you need to cancel multiple entries.

**Comment by turtlexiv** [comment]
Closed by emperorshammer/tiecorps#441.
