### ISSUE TITLE
[TC-3: COO] [Administration > Submit Activity > "Report a winning multiplayer PvP match"/"Report a winning multiplayer PvE (Co-Op) match"

### ISSUE THREAD

**Issue by TCTails** [emperorshammer/issues-incoming-queue#110]
Requesting Officer: FA Miles Prower (Combat Operations Office/TC-3)
Site To Update: TIE Corps (http://tc.emperorshammer.org)
Area To Update: Administration
Section To Update: Submit Activity
Pages To Update: 
"Report a winning multiplayer PvP match" https://tc.emperorshammer.org/submitmp.php
"Report a winning multiplayer PvE (Co-Op) match" https://tc.emperorshammer.org/submitmp.php?mode=pve
Update Type & Amount: 2 additions
Update:
Please insert the following submission rule to each page:
Matches must be submitted no later than 72 hours from their completion. Anything past a 24 hour allowance period is to be denied.
Source of rule: https://wiki.emperorshammer.org/COO:Combat_Operations_Manual

Thank you,
FA Miles Prower

**Comment by turtlexiv** [comment]
Implemented on PR emperorshammer/tiecorps#539 .
