### ISSUE TITLE
Imperial University problem(s)

### ISSUE THREAD

**Issue by EHSilvius** [emperorshammer/issues-incoming-queue#113]
If you are in the indes site for SM/5 (https://www.emperorshammer.org/iu/sm5/index.htm) 

and clicking on the link for the course test your are not linkedto the test. instead you have a link to the main page of the Vehicle Course - Stage 4 (VS4). (https://tc.emperorshammer.org/university.php?id=199)

the link for SM/5 course is https://tc.emperorshammer.org/university/exam.php?course=204

Respectfully 
Silvius

**Comment by turtlexiv** [comment]
Resolved a number of weeks ago with a redirect to the main IU page; further updates will be by the TO.

Thanks for reporting the issue.
