### ISSUE TITLE
Editing award recommendations

### ISSUE THREAD

**Issue by Solohan50** [emperorshammer/issues-incoming-queue#119]
When editing a previously created award recommendation, you are unable to edit the medal that's being given.  This means that if you make a mistake in the award recommendation, you need to cancel the request and recreate it from scratch.  It's not a huge deal by any means, but it would be nice to fix if possible.

**Comment by turtlexiv** [comment]
The approval chain is calculated based on the particular award; changing the award type necessitates a new approval chain which is currently a bit complex. Eventually I'd like to resolve that, but for now locking the award was an easy interim solution.
