### ISSUE TITLE
Return denied screenshots to member for review and resubmittal

### ISSUE THREAD

**Issue by TheBlackxRanger** [emperorshammer/issues-incoming-queue#124]
Once a submission (legions) is denied, currently members receive a notification that their submission was denied however it does not currently provide the screenshot in question. This requires members to hunt down the aforementioned screenshot in their submitted pages.

A solution to expedite and assist members would be to include the screenshot in the denial message for more efficient resubmissions

**Comment by turtlexiv** [comment]
I don't think jamming the screenshot image into the notification makes sense, but how about I just put a link to that match's information page?

**Comment by TheBlackxRanger** [comment]
That could work!
