### ISSUE TITLE
Recently started competitions show denied ones too

### ISSUE THREAD

**Issue by FearsomeTaurus** [emperorshammer/issues-incoming-queue#125]
![Screenshot_20220926-175203_Chrome](https://user-images.githubusercontent.com/114425701/192324677-4f8db0e2-a0c5-4d64-a369-5fa3ae14049c.jpg)
![Screenshot_20220926-175943_Chrome](https://user-images.githubusercontent.com/114425701/192324873-0983285a-c202-4312-9fa4-023f9c5d8327.jpg)

While browsing through the comp announce page, i noticed one of my denied competitions, show up under the recently started page.
That seems a bit odd, right?

**Comment by turtlexiv** [comment]
Fixed. https://tc.emperorshammer.org/changelog.php
