### ISSUE TITLE
Imperial University Request

### ISSUE THREAD

**Issue by kazraran** [emperorshammer/issues-incoming-queue#126]
When logged in, it shows the completed courses under "Your Transcript".  This is great.  Is it possible to have an indication of the courses where I have a set of saved but not submitted answers?  And for that matter, a submitted, but ungraded, set of answers?

Say, green for passed classes, red for submitted but ungraded, and yellow for saved but not submitted?

https://tc.emperorshammer.org/university.php

-Kaz

**Comment by turtlexiv** [comment]
This feature is already available at https://tc.emperorshammer.org/university/history.php.
