### ISSUE TITLE
Competitions Center: Ending Comps Bug

### ISSUE THREAD

**Issue by vapinvanman** [emperorshammer/issues-incoming-queue#127]
Noticed that in the Ending Comps featured area, the Warrior Write Off Comp was shown with 2 days to go. I clicked on it, and it was a denied comp.
TL-DR: Bug showing "Denied" Comps in the Featured section for "Ending Comps"

**Comment by turtlexiv** [comment]
Fixed. https://tc.emperorshammer.org/changelog.php
