### ISSUE TITLE
Feature request: Email notifications when an exam is ready for grading.

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#131]
Minor feature request for the Training Office.
Requesting that email notifications be sent to Professors of courses when exams are ready for grading.  This would allow Professors to not have to check the Training Dashboard as frequently and allow for decreased grading times for less active Professors.  Possibly allow for the toggling of this notification option, should Professors not wish to receive such emails.

**Comment by turtlexiv** [comment]
Fixed. https://tc.emperorshammer.org/changelog.php
