### ISSUE TITLE
Feature request: Professor listed on "Exams Pending Grading"

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#132]
Minor feature request.
Requesting that the Training Office's "Exams Pending Grading" screen include a column indicating the Professor responsible for teaching a particular course.  This would allow Training Staff to better identify which courses need to be graded by Staff without having to manually check if a course has an active professor.

**Comment by robertehogan** [comment]
This specific feature request/change would be of great help to the Training Office if it was completed first out of our requests.  No rush at all of course, but of the four updates we've added here, this one is of the most immediate concern since we are actively bringing on more Professors.  Specifically, replacing the Exam Version column with the Professor seems like the most simple and effective solution, since exam version numbers are not very important while actively grading.

**Comment by turtlexiv** [comment]
Fixed. https://tc.emperorshammer.org/changelog.php
