### ISSUE TITLE
Feature request: Exam grading officer displayed on "Historical exam submissions"

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#134]
Minor feature request.
Request that the Exam version number no longer be displayed on the "Historical exam submissions" screen and instead replace it with the name of the officer who graded the exam.  The exam version is not used often within the Training Office and viewing the professor from this screen would be beneficial for Training Staff.

**Comment by turtlexiv** [comment]
Fixed. https://tc.emperorshammer.org/changelog.php
