### ISSUE TITLE
Selecting "Submit another PvE match for these players and game platform" reorganizes group in ascending order by number of kills in previous match. 

### ISSUE THREAD

**Issue by gytheran** [emperorshammer/issues-incoming-queue#135]
I know the goal here is to have players on the LoS/LoC submission form default to alphabetical order, so I am reporting this. Originally, submitting another PvE match for the same group organized the names on the submission form in descending order by number of kills that occurred in the previous match. This order has reversed, and is now arranging the names in ascending order by previous kills. I can verify this is occurring with the Multiplayer PvE submission form.

**Comment by gytheran** [comment]
If kills are equal and names are in alphabetical order, the order of the next match submission does not change.

**Comment by turtlexiv** [comment]
Fixed. https://tc.emperorshammer.org/changelog.php
