### ISSUE TITLE
Add completion markings per IU category

### ISSUE THREAD

**Issue by TheBlackxRanger** [emperorshammer/issues-incoming-queue#137]
It would be a nice visual to see completed course categories if you have completed all sub courses.

Here is a mock up of how it would show with check marks

additionally, implementing a tracker or way to display percentage of progress per category and overall category

![image](https://user-images.githubusercontent.com/74426625/202877884-905347fe-e4f3-426b-bdb6-33f91dde3d9d.png)

**Comment by turtlexiv** [comment]
This would be rather complicated due to the way the categories work, nor do I think it's really the intended use of the categories anyway.

What is the use case as opposed to just scrolling down and seeing the full list of courses you've completed?

**Comment by TheBlackxRanger** [comment]
Basically if we ever had something like degrees or rewards for competing categories it would look nice on paper but that's about it. I'm not sure if that's anything planned 
 
 
  On Wed, Dec 7, 2022 at 6:14 PM, ***@***.***> wrote:   


This would be rather complicated due to the way the categories work, nor do I think it's really the intended use of the categories anyway.

What is the use case as opposed to just scrolling down and seeing the full list of courses you've completed?

**Comment by turtlexiv** [comment]
The Training Office is currently working up something along those lines that I already have the draft specifications for.
