### ISSUE TITLE
INPR Tab in Pilot Profile - Minor Spelling Error

### ISSUE THREAD

**Issue by GenieEH** [emperorshammer/issues-incoming-queue#141]
Alignment and attiude: should be Alignment and attitude:

(missing a t)

**Comment by TheBlackxRanger** [comment]
adding to the spelling error, on the legion submission page the word certify has a typo (cerify)

![image](https://user-images.githubusercontent.com/74426625/205964249-3bbadd61-46fd-4393-96f8-0636115a2c1d.png)

**Comment by turtlexiv** [comment]
Thanks!
