### ISSUE TITLE
New feature: Squadron Transfer Requests

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#143]
Suggestion to implement a squadron transfer request for the database (from myself and LegionX).

This is intended to solidify the chain of command and mitigate any issues of pilots circumventing the chain of command and not informing CMDR's of their intended transfer.  This would also standardize the process by creating a single process for transfers.

The suggestion here is to have any pilot assigned to squadron (FL and below) be allowed to submit a transfer request.  This request would specify the squadron they wish to transfer to, along with comments from the pilot.  This request would be then sent to both the pilot's current CMDR and the CMDR of the other squadron, with both being required to approve the transfer request for it to proceed.  If both CMDR's approve the request (CMDR's could also include comments?), the approved request is sent via notification to the TCCOM.

**Comment by MrPliffles** [comment]
There's already a single process for transfers outlined in the TCPM, and this isn't it. Disapproved from my side, also disappointed that this was submitted to the IO without being passed by me first.

**Comment by robertehogan** [comment]
Based on the previous TCPM.  The current TCPM outlines a process different than the one described.

**Comment by turtlexiv** [comment]
@MrPliffles is this not a duplicate of emperorshammer/tiecorps#94?

**Comment by MrPliffles** [comment]
Yes and no, because it's describing a different approval process. The process described here isn't what I'd want.
