### ISSUE TITLE
Button/label clipping on Killboard Selection

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#147]
Similar to #145 and #146.
On killboards.php, the buttons and labels for the killboards can extend beyond the screen on certain smaller screen sizes.

**Comment by turtlexiv** [comment]
I can't reproduce this; can you screenshot it?

**Comment by robertehogan** [comment]
<img width="800" alt="Screenshot 2023-03-19 at 2 45 39 PM" src="https://user-images.githubusercontent.com/82784247/226211626-a7aba427-8d8f-4971-b2b8-c4c8f04941a4.png">

**Comment by turtlexiv** [comment]
Oh, different page than I was thinking - gotcha.
