### ISSUE TITLE
CoB Eligibility Board include squadrons

### ISSUE THREAD

**Issue by VictorianVader** [emperorshammer/issues-incoming-queue#148]
Currently, the CoB Eligibility Board lists the pilot and their total number of missions/legions. Being able to quickly tell which squadron a pilot is in would make it that much easier for CMDRs to quickly scan for pilots in their squadron.  Would it be possible to:

1. List the pilot's squadron as another data column?

OR

2. Only list pilots that fall under the user's purview?  For example, as Rho CMDR I would only need to see Rho pilots who are CoB eligible.

**Comment by robertehogan** [comment]
Just throwing out another option/opinion, possibly grouping the pilots by their active unit (i.e. Rho Squadron, Sin Squadron, Reserves, Inactive Reserve, etc.) with a sub-header for each?
