### ISSUE TITLE
Gonk / ATR API not showing correct values for users with > 1 page.

### ISSUE THREAD

**Issue by SmTaUcM** [emperorshammer/issues-incoming-queue#15]
https://gonk.vercel.app/squadronActivity?squadronId=64&startDate=2021-05-01&endDate=2021-05-13
Listing 3-2 LCM SkyShadow #6958 is returning erroneous data due to ""hasMore": true," being set for all 19 pages instead of just pages 1 & 2. - Suspect pages 3 to 19 are also being counted in the calculations which are repeats of page 2.

Line 92 of activis.js calls: if (activity.hasMore && page < 20) { do stuff }

looking at the code, the best I can tell is that it looks for up to a max of 20 pages. I should have only 2, but because 'hasMore' = true is set, it's repeating my data a further 17 times? Something like that anyways.

**Comment by ajacksified** [comment]
Fixed.
