### ISSUE TITLE
Personnel Record > Awards: Images squished

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#152]
On a member's profile in the awards section, on smaller screen sizes (but bigger than mobile), the medal images displayed become squished as the height remains the same but the width gets smaller.  This mainly affects images which are square (i.e. BS, SS, GS, IS, LoC, LoS, OoV).  The impact on non-square images (i.e. MoC, MoT, MUA) appears to be minimal.

**Comment by turtlexiv** [comment]
Closed by emperorshammer/tiecorps#640 .
