### ISSUE TITLE
Timed Test Management dropdown options hidden

### ISSUE THREAD

**Issue by Cochleardestruction** [emperorshammer/issues-incoming-queue#153]
![Dropdown_menu_issue](https://user-images.githubusercontent.com/125910114/220169735-0795c42b-a5ca-403a-905e-955c18a353f2.png)
Dropdown menus hide themselves behind the frame of the webpage. Cannot interact or view options of bottom two Timed Test entries (needed for reviewing submissions & altering tests.)

LCM Bonebolt

**Comment by turtlexiv** [comment]
Thanks for the heads up, we'll look into it.

**Comment by turtlexiv** [comment]
Problem has been identified and a fix will be pushed soon.
