### ISSUE TITLE
Uploading image assets

### ISSUE THREAD

**Issue by Solohan50** [emperorshammer/issues-incoming-queue#154]
CMDRs don't appear to have the "View uploaded image assets" link in their Management page.
![Screenshot_2023-02-24-14-20-47-29_3aea4af51f236e4932235fdada7d1643](https://user-images.githubusercontent.com/96559232/221304937-82b09fab-cc2b-4f72-a2d5-eda7beb51b0b.jpg)

**Comment by turtlexiv** [comment]
The link does not appear because you did not have any uploaded assets; however, it's probably more intuitive to always show it since it leads you to one of the ways of uploading new ones.
