### ISSUE TITLE
XWA .bat patches need commands updated

### ISSUE THREAD

**Issue by Solohan50** [emperorshammer/issues-incoming-queue#164]
Currently, our XWA patches that are in .bat format require a command to be manually changed before these patches will work on modern versions of Windows.  The changes that need to be done to these patches are documented here:

https://wiki.emperorshammer.org/Troubleshooting:_Games#Modify_Ship_Patch

**Comment by turtlexiv** [comment]
All of these have been updated as of... whenever I did them, and forgot to close the issue :-P
