### ISSUE TITLE
Timed Test Apostrophe Code

### ISSUE THREAD

**Issue by VictorianVader** [emperorshammer/issues-incoming-queue#166]
Timed tests display code instead of apostrophes when viewing the questions. Confirmed for both test creator/manager and test taker.

![Screenshot_20230429-080008](https://user-images.githubusercontent.com/102089487/235301406-babb51f0-7397-4b93-9544-5445b92d2fd1.png)

**Comment by VictorianVader** [comment]
Quotation marks also show up as code.

![quotes](https://user-images.githubusercontent.com/102089487/236366418-01ef95ca-17d4-43b4-b4f2-3316182608f2.png)

**Comment by turtlexiv** [comment]
Thanks for the report.  A fix is in the review queue.
