### ISSUE TITLE
Award Recommendations - Update Quantity Doesn't Work When Editing

### ISSUE THREAD

**Issue by Solohan50** [emperorshammer/issues-incoming-queue#167]
When editing a previously submitted Award Recommendation, you are able to edit the Quantity field but this isn't actually reflected when you save the edit.  For instance, if I edit an ORA rec and want to change the Quantity from 2 to 3, I can change the Quantity field to 3 but when I save the rec it still shows as quantity 2.

**Comment by turtlexiv** [comment]
Thanks for the report- fixed!
