### ISSUE TITLE
Fiction Upload Uncaught Error

### ISSUE THREAD

**Issue by vapinvanman** [emperorshammer/issues-incoming-queue#169]
Trying to upload a fiction, I input title, add file, and click upload with no other boxes filled in. Both public and EH only return an uncaught error when trying to post. Error was logged 3 times, the most recent timecode was: 2023-05-07T05:31:37+00:00.

**Comment by vapinvanman** [comment]
txt uploads work, appears .pdf upload has an issue.

**Comment by turtlexiv** [comment]
Forgot to load the new dependencies - try now.
