### ISSUE TITLE
TC Core IU Exam 'return key' bug

### ISSUE THREAD

**Issue by SmTaUcM** [emperorshammer/issues-incoming-queue#17]
LT RedBaron has identified a bug when taking the TC Core IU exam at:
https://www.emperorshammer.org/test.php?id=122
Whereby pressing return for a new line whilst typing in certain text fields instantly submits the exam even though incomplete.
Text field #9 is effected and reproduceable and I suspect other text fields will give the same result.

**Comment by ajacksified** [comment]
This isn't a bug, this is standard browser behavior: pressing enter in _any_ non-multiline text box results in form submission. We should not break this behavior. I'd suggest:

* Filing a ticket with the TO to update some of these fields to be multi-line textboxes
* Implement a confirmation dialog if a test is submitted without every field being filled in, to ask the user if they'd prefer to submit anyways, save for later, or cancel the submission operation. We can have a "submit anyways" / "cancel" dialog easily in the current website, but we should consider the three-way option (submit, save, cancel) for the new website.
