### ISSUE TITLE
Fiction Center - Plaintext option instead of markdown

### ISSUE THREAD

**Issue by TheBlackxRanger** [emperorshammer/issues-incoming-queue#171]
When copying prior fiction pieces and uploading to the site, unintended markdown is added which can have an impact on how the story is displayed. Please see below example (with permission), where majority of the formatting appears to be lead by a # making text display as a header

https://tc.emperorshammer.org/view_fiction.php?id=201

Suggestion would be to add an ability to turn off markdown or post in plaintext if desired.

**Comment by turtlexiv** [comment]
The main problem is using superfluous characters in the content, specifically `===` being used as a section divider.

I'm not convinced that adapting the tool to encourage poorly formatted content is the right answer as opposed to fixing the content (in this case, simply don't *add* unnecessary stuff).

**Comment by turtlexiv** [comment]
https://github.com/emperorshammer/tiecorps/pull/681 will mitigate some of the text entry problems and should satisfy this issue.
