### ISSUE TITLE
Email Notification when a new member joins not working

### ISSUE THREAD

**Issue by GenieEH** [emperorshammer/issues-incoming-queue#173]
SL Snuffy got assigned to Lambda but I did not receive any notification even though 
https://tc.emperorshammer.org/editaccount.php?tab=notifications 

Member is Reassigned is tagged for both self and others.

**Comment by turtlexiv** [comment]
Verified notifications and emails are being properly generated.  Please double check your spam folder and/or client settings; there is nothing more on our end to check.
