### ISSUE TITLE
Colour Coding for different types of Website Notifications

### ISSUE THREAD

**Issue by GenieEH** [emperorshammer/issues-incoming-queue#174]
It's very difficult to see some of the more important notifications on our website. 
Can we introduce a colour shade as a background colour for each row? 

As in, to assign a colour to each type of notification
e.g. assignments = green background colour
HS approved = yellow 
BSFs = blue 
etc

**Comment by turtlexiv** [comment]
Verified notifications and emails are being properly generated.  Please double check your spam folder and/or client settings; there is nothing more on our end to check.

**Comment by turtlexiv** [comment]
There are currently 30 notification types with more always being added. This, plus the definition of 'important' probably varying greatly depending on the user, probably makes this impractical.
