### ISSUE TITLE
Change discord id validation

### ISSUE THREAD

**Issue by moff-wildfire** [emperorshammer/issues-incoming-queue#175]
Discord is getting rid of the hash 4digit number suffix and now restricting names to lowercase letters, numbers, periods, and underscores.

https://discord.com/blog/usernames

**Comment by moff-wildfire** [comment]
This impacts at a minimum the member profile page for EHTC

**Comment by TheBlackxRanger** [comment]
I am unable to update my discord name 
![Screenshot_20230612-103954](https://github.com/emperorshammer/issues-incoming-queue/assets/74426625/9322773f-0a9c-4244-b836-c109689f5670)
