### ISSUE TITLE
ID Line Awards

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#181]
It would seem that TC-associated awards (such as the Gold Star) that are awarded to EH profiles do not display on the TC ID line.  For example, while I have been awarded a GS on my EH profile, my TC profile's ID line does not have "GS", despite the Gold Star being a TC award.  Conversely, for FA Pickled Yoda, his TC ID line shows a GOE, but his EH ID line does not show it, despite the GOE being an EH award.  I am not sure if this could possibly be because the ID line only takes into account the awards given to that profile irrespective of the medal's group status?  For these instances, though, the "Awards" tab in the profile displays all of the awards correctly.

**Comment by ajacksified** [comment]
Fwiw, when debugging, my GS shows up:

> GOE/GSx2/SSx12/BSx17/PCx9/ISMx10/IAR/MoT-2gh-bh/MoI-BC/MoC-2doc-3poc-4goc-4soc-27boc/TUA/MUA-BW/IS-PW-12GW-19SW-26BW-2CW-4GR-12SR-18BR-2CR/ORA-2C/LoC-2PS/LoS-1PS/DFC/CoE/CoLx3/CoB/OV-15E [Paladin] [Ace 4th] [Campaigner 1st]
{TCCORE-COE-MCBS-SM/3/5-WIKI-XAM}

**Comment by turtlexiv** [comment]
It's less of a bug, and more of a design choice that I'm still working through.  ID lines currently only display awards for that specific character.  (The awards page was updated with today's update to show awards from other characters in specific circumstances).

**Comment by turtlexiv** [comment]
Lots of changes made since this issue was opened; all character profiles now show EH awards. Closing this as complete unless we note any other areas needing improvement.
