### ISSUE TITLE
View most recent fiction uploads 

### ISSUE THREAD

**Issue by TheBlackxRanger** [emperorshammer/issues-incoming-queue#186]
I had an idea where there's a place to see most recent fiction uploads so people can read the latest entries without members having to dig for them on respective pilots. A most recent upload section would be cool to see for both fiction and graphics

**Comment by turtlexiv** [comment]
Technically, that is exactly what the main fiction center listing shows... https://tc.emperorshammer.org/fiction.php

Were you thinking something else?

**Comment by TheBlackxRanger** [comment]
Oh! I guess that shows how often I check the fiction center LOL. Yeah that'll cover it
