### ISSUE TITLE
Minor issue - No means to remove profile picture.

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#189]
There does not appear to be any way to remove an "avatar" from an EH profile (i.e. remove a TC character profile picture).  Clicking the "update profile" button on ```editaccount.php?tab=character``` when an image is not selected simply defaults to the original image assigned to the character.  If there is a means to remove an avatar, it might benefit from additional explanation on how that should be done to make sure that it is as accessible as possible to members.  If there is not currently a means for this, ```uploaduni.php``` might allow for an easy copying of the PHP functionality to this specific application?

**Comment by turtlexiv** [comment]
Updated; see https://tc.emperorshammer.org/changelog.php
