### ISSUE TITLE
Wiki potential improvement - DB website link

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#192]
Recommend that similar to how the EH website ("Emperor's Hammer") and TC website ("TIE Corps") are linked on the Wiki sidebar, the DB website also be linked.  This would serve to reinforce the DB as an active subgroup and provide additional public-facing linkage to the site.

**Comment by GB-Hijacker** [comment]
Great idea!  A link to the DB site has been added to the sidebar
