### ISSUE TITLE
Minor possible improvement - EH-wide component search

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#195]
With the current website, each EH domain (tc.*, db.*) has their component search limited only to their members.  However, the primary domain (emperorshammer.org) similarly follows this practice, essentially limiting that component search to EHCS members.  Thus, this would be a suggestion to possibly adjust this on the main EH domain, making it possible to search for any member/character (EH, TC, or DB) with the component search function.  This would allow for awards coming from EHCS to be able to all be recommended in one place without having to switch to the TC or DB websites in order to make the recommendation.

**Comment by turtlexiv** [comment]
Do you know if it's been like this since the DB site transition, or is it a recent thing?

**Comment by robertehogan** [comment]
I am not sure - the first time this came up for me personally was very recently, but that was the first time I was using the main EH domain to recommend awards.

**Comment by turtlexiv** [comment]
Looks like we changed the behavior in emperorshammer/tiecorps#733 .

**Comment by turtlexiv** [comment]
PR is linked.
