### ISSUE TITLE
Move "join subgroup" link/button to Management portal

### ISSUE THREAD

**Issue by TheBlackxRanger** [emperorshammer/issues-incoming-queue#196]
Morgan and I were discussing the join subgroup button in the edit profile and preferences, we found that it's pretty tucked away from most members to find. Historically I've seldom used the edit profile button aside from INPR. https://tc.emperorshammer.org/editaccount.php?tab=profile

We were curious if there would be a benefit to moving the join subgroup button/portal up one link to the main management portal https://tc.emperorshammer.org/management.php as Members frequently visit this page in comparison, thus increasing odds of joining sub groups.

**Comment by turtlexiv** [comment]
I kind of intentionally stashed it a little out of the way, with the idea that we don't really want people creating characters in new subgroups without really intending to do so and knowing what they're doing.  It's also in theory a one-time use function (at least right now, with only two active subgroups) so didn't need to take up space in the main management menu.  Happy for discussion on it though.
