### ISSUE TITLE
Minor issue - IU/Qualification notifications don't always go to CoCs

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#197]
When a member completes an IU course or qualification, not all of their chains of command are notified, only the one set as "default character".  For example, a VA profile in the EH might have their EH superior get an email, but their character as a COL in the TIE Corps would not have any of their TC CoC getting an email.  I would assume that since IU courses/qualifications are listed as "appl[ying] to all of this member's characters" that all relevant superiors would seek to be notified of this activity through the usual methods.  However, since newly-completed IU courses are accessible through other means during monthly evaluations, this is likely not a pressing issue to fix.

**Comment by turtlexiv** [comment]
This is a known limitation and you are correct - currently it's set up where the notification goes to the default character.

Sending this to all of the characters is probably the right approach.

**Comment by turtlexiv** [comment]
Closed by emperorshammer/tiecorps#745 .
