### ISSUE TITLE
Academic Papers section added to Academics tab

### ISSUE THREAD

**Issue by EH-SylasPitt** [emperorshammer/issues-incoming-queue#198]
For students that have completed Graduate+ courses, allowing them to publish their thesis and dissertations on their profiles (separately from the Fictions section). 

Document could be uploaded by TO, CA:TO or TOA to the member's profile, restricting members from publishing their own to avoid any misunderstanding or miscommunications.

**Comment by turtlexiv** [comment]
I like this idea.
