### ISSUE TITLE
IS VI tracker

### ISSUE THREAD

**Issue by TCPhoenixBerkana** [emperorshammer/issues-incoming-queue#208]
Existing tracker example: https://tc.emperorshammer.org/comps/imperialstorm.php?free=379&end=2022-04-20&hs=94403

Based off this example... the changes would be as follows (all for a 48 hour period)

**In the Summary at top**
- Report the SUM of all HS%'s (user can continue to specify for the HS used in the calculation as it currently does)
- Add up SUM of all the individual scores from the breakdown per day, split into LoC/LoS per day (much as it does now)

**In the Breakdown**
- Report each pilots HS%
- List the score per pilot per day by LoC/LoS (so the change from now would be to multiply the number of legions by the platform score)

**Comment by turtlexiv** [comment]
I also assume these need to be switched to battlegroups?

**Comment by TCPhoenixBerkana** [comment]
Yes pls! Sent from my iPhoneOn 12 Feb 2024, at 19:31, turtlexiv ***@***.***> wrote:﻿
I also assume these need to be switched to battlegroups?

**Comment by turtlexiv** [comment]
I need the platform values as well.

**Comment by TCPhoenixBerkana** [comment]
Should be the same as AotTC.Sent from my iPhoneOn 15 Feb 2024, at 22:40, turtlexiv ***@***.***> wrote:﻿
I need the platform values as well.

**Comment by turtlexiv** [comment]
Closed by emperorshammer/tiecorps#788
