### ISSUE TITLE
Single Mission - Mission Completion Tracking - TIE Fighter

### ISSUE THREAD

**Issue by GenieEH** [emperorshammer/issues-incoming-queue#21]
Noticed that for my pilot (Genie), the TIE Fighter missions completed are not recorded in the Monthly Killboard.

![](https://cdn.discordapp.com/attachments/703744980438483026/854594470335348736/unknown.png)

**Comment by turtlexiv** [comment]
This should now be resolved on the new site where everything has been recomputed.
