### ISSUE TITLE
SL to LT Promotion Recommendation Permission

### ISSUE THREAD

**Issue by MrPliffles** [emperorshammer/issues-incoming-queue#210]
Summary: Allow SQXOs and FLs to recommend promotions from SL to LT for pilots in their squadron (not for pilots in other squadrons if avoidable)

Rather than having SL to LT promotion recommendations only be able to come from the CMDR, the idea is to allow SQXOs and FLs to recommend them as well so that the SL gets their promotion as soon as possible. It's being suggested for SL to LT specifically because that promotion is supposed to be the quick and easy one to get help get pilots "hooked" on the TIE Corps, which it doesn't do as effectively the longer it gets drawn out. Not drawn out because of any failure on the part of everyone involved, the thought is that we can better account for leaders not being online each and every day because we don't need to set that kind of expectation.

**Comment by turtlexiv** [comment]
Permissions added. The member lookup on the form is constrained to the single unit similar to CMDRs.
