### ISSUE TITLE
New TIE Corps Primary Games: Destiny 2 and Star Wars Battlefront Classic Collection

### ISSUE THREAD

**Issue by MrPliffles** [emperorshammer/issues-incoming-queue#211]
Both games received unanimous approval by the TC admirals in #tc-admiralty-polls, FC approval came during a meeting I had with him on 3/8.

Destiny 2 will have both LoCs and LoSs.

Battlefront Classic Collection has online PvP but not PvE, I believe, so we'll keep it to just LoCs for now. It has split screen co-op, so we might see requests for support for that.

**Comment by ajacksified** [comment]
The SO would like to enable up Battlefront Classic as well while you're at it. We're not going to pick up Destiny at the moment.
