### ISSUE TITLE
Printable Characters in Member Names

### ISSUE THREAD

**Issue by MrPliffles** [emperorshammer/issues-incoming-queue#214]
<img width="331" alt="2024-03-14 19_48_07-Post News Article - TIE Corps" src="https://github.com/emperorshammer/issues-incoming-queue/assets/64677934/213c4e79-27a3-495b-9242-4d8cc85f10cc">

If non-printable characters can't be used in news post titles, should we allow them in names? Can work around it by not using the member's name in the title of a news post, but it might make things easier in the long run if we prevented them from putting a non-printable character in their name to begin with (the join form).

**Comment by turtlexiv** [comment]
Currently assessing this. As a primarily English language organization, having member names that use characters most people can't readily type seems like a pain. This is admittedly somewhat anti-internationalization but there are practical considerations when we're referring to member names.

The code accepts unicode, so currently you could use emojis or other dumb shit in your name that we obviously wouldn't continue to allow.

![image](https://github.com/emperorshammer/issues-incoming-queue/assets/37425083/948b5288-858d-40c5-b6ac-f3791c4d6bd8)

Additional feedback is welcome.

**Comment by MrPliffles** [comment]
My only real concern is having a member's name that we can't include in a headline without changing its format (and thus it not being the same name, really). If the headline field rejects all accented characters like the ones our international members might use, maybe there are two changes to make?

**Comment by turtlexiv** [comment]
After checking, I can't actually substantiate that there is a problem with putting his name into a news post.

![image](https://github.com/user-attachments/assets/891b7189-419c-4f67-82e2-080d0fecf137)

The question about 'weird' unicode characters in a name is still an open and separate question.

**Comment by turtlexiv** [comment]
Actually, this *is* a problem on production. I'll have to dig into why.
