### ISSUE TITLE
Fatal Error while attempting Award Mangement

### ISSUE THREAD

**Issue by MRclarkTC** [emperorshammer/issues-incoming-queue#217]
![grafik](https://github.com/emperorshammer/issues-incoming-queue/assets/167787386/15aa2c62-3121-42e1-8b47-0dfa042bace5)

Above error while trying to enter the _Manage Awards and Award History_ page for a pilot via the Member Record Mangement.

First occurance was Friday, April 19th. Attempts were made with mutliple pilots to the same result. All other links seem to be working.

**Comment by turtlexiv** [comment]
Fixed.
