### ISSUE TITLE
Automate the IWATS email sent to new pilots

### ISSUE THREAD

**Issue by MrPliffles** [emperorshammer/issues-incoming-queue#220]
If this is possible, this would be a way to cut some time off of the TC's join process:

1. If "13 or older" is Yes, email the pilot using the template the TCCOM can edit via a Management stub. I'm picturing a big text field for the body of the email that would be sent, signature and subject could be automated. CC the TCCOM so they can see that it was sent out.

2. If "13 or older" is No, do nothing. TCCOM will receive the normal new pilot email notification but not the CC on the questions. That'll point to the No on "13 or older" and the TCCOM would carry out the next steps manually as usual.

This would automate the email part of the process I'm doing manually for new joins. This way they'd have a chance to start the IWATS scavenger hunt immediately instead of waiting for the TCCOM to be online. That'd only work if they receive the email successfully, but that's an improvement. I'd still reach out to them over Discord when I'm online, I started doing both email and Discord a while back.

**Comment by turtlexiv** [comment]
Issue linked to PR emperorshammer/tiecorps#835
