### ISSUE TITLE
Star Wars Hunters Support

### ISSUE THREAD

**Issue by MrPliffles** [emperorshammer/issues-incoming-queue#221]
The TCCS is in agreement on supporting Star Wars Hunters when it comes out, so I'd like to have that available in the system when the game launches to the rest of the world (it's available in some parts already) on June 4th. The COO will have details to announce, just need the IO to add the ability to choose it in screenshot submission dropdown menus.

**Comment by turtlexiv** [comment]
For new game platforms, we also need to know:
- Whether to allow submission of 0 kill games (i.e., the game has some objective-based wins).
- Whether to skip free-for-all checks (requirement that PvP FFA match winner has more kills than the second-place person).
- Abbreviation. (Probably SWH for this?)
- Which modes: PvP, PvE.
- Number of screenshots required for submission: 1 or 2.
- Whether to allow duplicate screenshots at submission. (Usually this is no, except for certain specific games that legitimately generate identical ones - EaW is an example.)

**Comment by MrPliffles** [comment]
- Allow 0 kill games, yes, as we're exploring basing the criteria on assists or score. This might change later but I doubt it.
- No FFA in this game that I'm aware of, so no need to make an FFA-related check (right?)
- SWH works great
- PvP only, no PvE in this game that I'm aware of
- 1 screenshot, no custom matches that I'm aware of and the scoreboard at the end of the match has all the info we need
- No duplicates

**Comment by turtlexiv** [comment]
Closed by emperorshammer/tiecorps#832 and emperorshammer/tiecorps#821
