### ISSUE TITLE
Notification Messages Name Variable

### ISSUE THREAD

**Issue by MrPliffles** [emperorshammer/issues-incoming-queue#224]
In Notification Messages, {$name} is returning the member's rank and name instead of just their name.

Examples:

- [EH] Welcome to the Emperor's Hammer {$subgroup}, {$rank} {$name}
- [EH] Welcome to the Emperor's Hammer TIE Corps, Cadet Cadet Fluffy

- Your name: {$name}
- Your name: Cadet Fluffy

**Comment by turtlexiv** [comment]
We should probably just remove the extraneous {$rank} in the subject.

**Comment by MrPliffles** [comment]
It's not just the Subject, this happens in the body of the message:

![name](https://github.com/emperorshammer/issues-incoming-queue/assets/64677934/03fdb3d6-1198-4ce5-914b-2a25868e38f1)

**Comment by MrPliffles** [comment]
Was going to remove the {!rank} from the Subject, but I found that I can't! Here's the error message:

![error](https://github.com/emperorshammer/issues-incoming-queue/assets/64677934/d837ebe3-b923-4e86-89aa-238f495d5bfa)

Same error keeps me from editing the message itself, naturally.
