### ISSUE TITLE
Wrong Description of Iron Star with Wings

### ISSUE THREAD

**Issue by JafanRuss** [emperorshammer/issues-incoming-queue#225]
In the description of the Iron Star (on the medalboard: https://tc.emperorshammer.org/stats.php?type=medals) is stated, that the ones with wings are reserved. I talked about it with VA Locke Setzer since there was a misunderstanding from my side about some awards and he said that they are for all comps in the primary games, not just flying ones. That wording seems to come from the time when there where only flying games as primarys but is not correct in the current context.
It's nothing that needs to be fixed urgently, but it's something that would be nice to be corrected to avoid future misunderstandings.

**Comment by turtlexiv** [comment]
Thanks for the report. Descriptions updated!
