### ISSUE TITLE
New Game: Helldivers 2 Support

### ISSUE THREAD

**Issue by MrPliffles** [emperorshammer/issues-incoming-queue#228]
Enabled modes: PvE only
Number of screenshots required for MP match submission: 1
Allow screenshot duplicates at submission time: No
Skip FFA checks: No
Allow 0 kill submissions: Yes
Initial Game Platform Management Value: 3.5

I'm saying one screenshot because of what I see in this example:

![helldivers](https://github.com/user-attachments/assets/c710009e-b269-4dc4-a82b-199830c4c7a8)

Between the Mission Completed message and the pilot's name, I think that's it for the level of support we're talking about. If we decide that the Requisition Slips earned need to be > X, that's in this screenshot too for the submitter and then we'll have an EABF2-like problem but it's okay.

**Comment by turtlexiv** [comment]
Closed by https://github.com/emperorshammer/tiecorps/pull/850
