### ISSUE TITLE
Add recently added TC primary games to game ownership list 

### ISSUE THREAD

**Issue by TheBlackxRanger** [emperorshammer/issues-incoming-queue#231]
![Screenshot_20241003-130858](https://github.com/user-attachments/assets/d80a7fb9-50e4-4091-b88a-480d60c33281)

Recommendation from maple

**Comment by turtlexiv** [comment]
Added: Destiny 2, Star Wars: Hunters, Helldivers 2, and Star Wars Outlaws. Please let me know any others I'm missing.
