### ISSUE TITLE
PLATFORM_MODIFIERS_EDIT_SG not granted for COO

### ISSUE THREAD

**Issue by MrPliffles** [emperorshammer/issues-incoming-queue#235]
COO needs to have that permission but it’s not on the COO’s profile.

![SmartSelect_20241220_152412_Chrome](https://github.com/user-attachments/assets/19f9aa8a-beac-4db4-8be7-6b5c97959fa7)
![IMG_3802](https://github.com/user-attachments/assets/d95e6ac8-08cf-4674-ab72-34a2d693ee0c)

**Comment by turtlexiv** [comment]
Permission added. See https://tc.emperorshammer.org/management/permissions_report.php.
