### ISSUE TITLE
MP - More data to gather

### ISSUE THREAD

**Issue by GenieEH** [emperorshammer/issues-incoming-queue#29]
To include Gamemode (that is to be able to differentiate between SWS Fleetbattles and SWS Dogfights)
Several other games have such different gamemodes such as SC and BF2

**Comment by turtlexiv** [comment]
Referring to COO office for comment.

**Comment by TCTails** [comment]
What would be the actual purpose though? The killboards don't draw from these extra identifiers and it's pretty easy to distinguish between Fleet Battles and Dogfights by screenshot.

**Comment by GenieEH** [comment]
competitions, and other metrics
In RtF 2021 for example we couldnt differentiate between the gamemodes (and as such award fleet battles more points than dogfights let's say)
Genie
    On Wednesday, 10 November 2021, 15:24:42 EET, Fleet Admiral Miles Prower ***@***.***> wrote:  
 
 


What would be the actual purpose though? The killboards don't draw from these extra identifiers and it's pretty easy to distinguish between Fleet Battles and Dogfights by screenshot.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by turtlexiv** [comment]
Closed per COO comment.
