### ISSUE TITLE
Profile Importing Issue with IS-Copper

### ISSUE THREAD

**Issue by robertehogan** [emperorshammer/issues-incoming-queue#3]
TTT3.  I have observed an issue when importing profile information from the database.  The Copper-level Iron Stars do not import from the database and the only way for them to be rendered is via manual input.  This has been observed on the following PINS: 55859 (CR missing), 55730 (CW and CR missing), 12292 (CR missing), 55900 (CR missing).  All other Iron Stars appear to be imported successfully.

**Comment by Stryker359** [comment]
I have also come across this issue on my profile (12292) - importing brings other medals in, but the Coppers have to be added manually.

**Comment by turtlexiv** [comment]
We haven't added them to the API yet.  Thanks!

**Comment by SmTaUcM** [comment]
Issue transferred to emperorshammer/TTT3 as:
Pilot API to be updated to return newly added awards. (IAR, TUA, MUA & IS-CR/W) #63

I'll keep the issue open here for reference while Beta testing continues.

**Comment by turtlexiv** [comment]
New medals implemented at 2e62e01.
