### ISSUE TITLE
MP - UI Suggestion

### ISSUE THREAD

**Issue by GenieEH** [emperorshammer/issues-incoming-queue#30]
When submitting an LoC or LoS, to return you back to another submit with 
a) the game, 
b) gamemode (new feature) 
c) and all the pilots you had selected in the last LoC/LoS **pre-selected already.**

Reason: more often than not you tend to play several games for 1-2 hours with the same players more or less.

**Comment by turtlexiv** [comment]
Feature is already implemented in development branch.
