### ISSUE TITLE
Cannot Access Combat Operations [MinosRel]

### ISSUE THREAD

**Issue by TCTails** [emperorshammer/issues-incoming-queue#34]
When making use of the Staff Officer Dashboard > Combat Operations link, the error "You do not have permission to manage combat operations." appears. Issue submitter is Combat Operations Officer and should definitely have access to manage combat operations.

COO/FA Miles Prower/TC-3/VSDII Aggressor
GOEx2/GSx2/SSx3/BSx5/PCx8/ISMx20/MoI-BC/MoC-5doc-5poc-7goc-7soc-53boc/MUA/IS-4GW-SW-8BW-CW-14SR-21BR-3CR/LoC-RS/LoS-RS/CoLx10/CoB/LoAx2/OV-15E

**Comment by turtlexiv** [comment]
Issue is already fixed, and will be available on next nightly release.
