### ISSUE TITLE
Deadlinks - Thread

### ISSUE THREAD

**Issue by TheBlackxRanger** [emperorshammer/issues-incoming-queue#49]
Starting a thread of deadlinks discovered and suggestions where possible

https://tc.emperorshammer.org/page/podcast -> receives 404 error
![image](https://user-images.githubusercontent.com/74426625/153819648-f518a893-68c6-4960-85cd-bf99f5e4c6c9.png)

Suggesting to point to either the airlock podcast https://www.youtube.com/playlist?list=PLSxjE6YJ9FF9xtnBpz9ds-LGa68OxRWvC or the predecessor podcast https://www.youtube.com/playlist?list=PLSxjE6YJ9FF-qgNv-05bSIEDK015EIpGh playlists

**Comment by turtlexiv** [comment]
Link switched to the YouTube channel; change to be reflected in hotfix-3.
