### ISSUE TITLE
TTT3 - Helmet Generation

### ISSUE THREAD

**Issue by SAKamjin** [emperorshammer/issues-incoming-queue#5]
- Helmet – Text – Pilot’s full name appears to be pulled versus the pilot’s nickname. Was this intentional?
- Helmet – Logo 1 – Image – bg. Transparent – fails to render with transparent background selected
- Once error occurs cannot return to Logo 1 in selection unless reset option is utilized

**Comment by SmTaUcM** [comment]
Point 1 raised as: emperorshammer/TTT3 Helmet text – Pilot’s full name appears to be pulled instead of the pilot’s callsign. #65
                           "Change helmet text to use callsign in place of pilot's name."

Points 2 & 3 - I'm unable to reproduce at initial glance. Please could you provide me with a step by step list of the actions that you took to cause the render fail including the image file you were using. Thanks in advance.

Great bug finding there :)

**Comment by SAKamjin** [comment]
Stuart,  Sure, below are the steps I followed. Open TTT3Click on ImportPIN 2758 and ImportClick Pilot’s HelmetText should populate with KAMJIN MAVER versus Pilot Nickname “Maverick”   Sector Admiral Kamjin “Maverick” Lap’lamizDark Side AdeptISP/SA Kamjin “Maverick” Lap'lamiz/IA-2/SSD AvengerGOE/GS/SSx2/BSx4/PCx4/ISMx3/MoC-3soc-6boc/IS-3BW-4SR-5BR/LoC-CSx9-Rx4/LoS-Rx2/CoLx3/CoB/OV-25E [Aquilifer] [Marksman 4th] [Beginner] {TCCORE-MCBS-MP/2-SM/2/3-XAM}{IU:C/TC, C/DB, C/DIR, S, UL, SM2, SM3, IO, LDR, SM/5, SFW, IST, HTML/1, AIM, M1, M2, HAD, GHA, THR, OSS, WPN, 2, XWAI, TIE, CA, MCBS, XAM, XMD} Adept Kamjin "Maverick" Lap'lamiz (Sith) / PCON / House Empire's Chosen of Clan Scholae Palatinae [SA: V] [GMRG: IV] [SYN: II] [ACC: Q] [INQ: VIII]ED / SB / GC / SCx2 / ACx3 / DCx4 / Cr:1D-3R-13A-7S-7E-4T / PoBx10 / CFx162 / CIx104 / CEx4 / CGx10 / LS / SoL{SA: MVLD - MVS - DPCM - DPCP - DPE}Duke of Juranno From: Stuart MacintoshSent: Saturday, April 24, 2021 5:00 AMTo: emperorshammer/issues-incoming-queueCc: SAKamjin; AuthorSubject: Re: [emperorshammer/issues-incoming-queue] TTT3 - Helmet Generation (#5) Point 1 raised as: emperorshammer/TTT3 Helmet text – Pilot’s full name appears to be pulled instead of the pilot’s callsign. #65"Change helmet text to use callsign in place of pilot's name."Points 2 & 3 - I'm unable to reproduce at initial glance. Please could you provide me with a step by step list of the actions that you took to cause the render fail including the image file you were using. Thanks in advance.Great bug finding there :)—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by SmTaUcM** [comment]
Kamjin, thanks for your quick reply. I've corrected the helmet callsign issue and believe I have corrected the rendering bug in the process. All fixes have been saved ready for testing at the next release.
