### ISSUE TITLE
Dead links on Pilot Statistics and Ranks page

### ISSUE THREAD

**Issue by 4ndr3** [emperorshammer/issues-incoming-queue#51]
Except for Squadron Battleboards none of the links on https://tc.emperorshammer.org/stats.php work

**Comment by turtlexiv** [comment]
I cannot reproduce, everything seems fine.

Can you screenshot what you're getting?

**Comment by 4ndr3** [comment]
Seems to be browser related. Getting WebKitErrorDomain:104 on Safari, not on Firefox
![Bildschirmfoto 2022-02-15 um 17 42 09](https://user-images.githubusercontent.com/3649886/154107779-978640ba-51b4-4c66-9d93-fe9fa4e004ba.png)
.

**Comment by turtlexiv** [comment]
I had to translate the page, but it seems like this is being generated by some kind of content blocker you have installed, probably an extension.  It's definitely not a server error.

**Comment by 4ndr3** [comment]
You're right. It was held up by AdGuard. I suppose you can close the issue. Leads to the question why these pages (and not others) would trigger an ad blocker.
