### ISSUE TITLE
Battle Review link returns 404

### ISSUE THREAD

**Issue by 4ndr3** [emperorshammer/issues-incoming-queue#52]
Battle Review links from Tactical Office's automated emails return 404. 

I think the problem is the changed PHP script name submitreview.php (in the email) vs. editreview.php (on the new site).
Example email:
https://tc.emperorshammer.org/submitreview.php?id=422&type=battle
Page:
https://tc.emperorshammer.org/editreview.php?id=422&type=battle

Side note on battle 422: there's something off with the character encoding. What the email actually links to has an extra "Â"
https://tc.emperorshammer.org/submitreview.php?id=422Â&type=battle
Characters were similarly added throughout the email:
Filename: _iw040.pltÂ 
Battle: XWAÂ-IWÂ #4Â - Rion's Shadow Campaign: Eliminate FriendshipÂ

**Comment by turtlexiv** [comment]
We'll add a redirect for the old link.

Everything looks fine for that battle on the new code, so probably no longer an issue.
