### ISSUE TITLE
Officer Report Error

### ISSUE THREAD

**Issue by kazraran** [emperorshammer/issues-incoming-queue#62]
Trying to access the page for Alpha Squadron reports returns a Server 500 error.  The others seem to work fine.

https://tc.emperorshammer.org/showreport.php?unit=7

**Comment by turtlexiv** [comment]
We have identified the problem and it will be fixed in the next push.  Thanks!

**Comment by turtlexiv** [comment]
Closed by emperorshammer/tiecorps#305.
