### ISSUE TITLE
Minor Header Error

### ISSUE THREAD

**Issue by vapinvanman** [emperorshammer/issues-incoming-queue#63]
![Website Glitch maybe](https://user-images.githubusercontent.com/100508532/155873148-16f22c4f-e166-44a2-8e44-e767d2d6bd21.PNG)
Gunners Mate are all "Gunner's Mate 4th"
Small issue, but just noticed it.

**Comment by turtlexiv** [comment]
Oops, that's weird.

We'll get it sorted - thanks!
