### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR

### ISSUE THREAD

**Issue by ColoDelste** [emperorshammer/issues-incoming-queue#64]
Attempted to submit BSF.

Uploading file went fine, displayed relevant info. When submit button pushed, following error appeared

![image](https://user-images.githubusercontent.com/99576682/155953470-f3e465c7-2ea2-43e3-b561-8703b5ce8599.png)

**Comment by turtlexiv** [comment]
Per user, problem has not reoccurred.
