### ISSUE TITLE
REQUEST: Drag/Drop Image Files

### ISSUE THREAD

**Issue by VictorianVader** [emperorshammer/issues-incoming-queue#77]
I used to be able to drag and drop image files into the upload sections instead of using the "choose a file" function (for example, uploading victory screenshots for LOC/LOS submissions).  Any way to add this functionality on the new site?

Thanks,
Westric Davalorn

**Comment by turtlexiv** [comment]
This is already a known issue and in the queue to be worked.

Closing as a duplicate of emperorshammer/tiecorps#258 .
