### ISSUE TITLE
Imperial Storm API

### ISSUE THREAD

**Issue by TCPhoenixBerkana** [emperorshammer/issues-incoming-queue#79]
For Turtle and Yoda to stand the Imperial storm API up again.
Previously at: https://api.emperorshammer.org/imperialstorm/

example url:
https://api.emperorshammer.org/imperialstorm/TIEF145/2021-08-15/25168

**Comment by turtlexiv** [comment]
Implemented as a page on emperorshammer/tiecorps#350
