### ISSUE TITLE
re-activate account form

### ISSUE THREAD

**Issue by Sienile** [emperorshammer/issues-incoming-queue#86]
Would be nice to have a "request to re-activate account" form instead of just a message to say to do it with no indication of how. The warning shows up when you try to login.

**Comment by tomsaunders** [comment]
```Returning former members should contact us on the [Emperor's Hammer Discord](https://discord.emperorshammer.org/) for assistance in recovering your profile.```

Is the message displayed on the login form , for the really old returning people. It mentions some instruction for making the request.

```'Your member account is inactive, and you are not able to login at this time. Please submit a request if you would like to have your member account reactivated.'```

Is the message displayed for the inactive profiles who do know how to login. This could be improved.

**Comment by turtlexiv** [comment]
Adding a slightly more verbose message.

A reactivation form wouldn't be very helpful, since any reactivation requires human review.
