### ISSUE TITLE
Battle Center not responding until close and relaunch (not reproducible)

### ISSUE THREAD

**Issue by Sienile** [emperorshammer/issues-incoming-queue#87]
Checking out the Battle Center after starting on the News page and clicking the link in the article to TAC Report #16, the Battle Center did not respond. I tried several times to click to see the listings for TC-TIE, but nothing changed other than the row tinting as I clicked to verify it was being pressed. Closing the tab and going directly to the BC from the News page resolved the issue. Just now to verify, I retraced the route from the failure instance and it behaved as normal. Possibly a random server glitch.

**Comment by tomsaunders** [comment]
The row changes colour on hover not on successful click so it could've been a few things... clicking in slightly wrong spot, clicking in right spot but the network was suddenly unresponsive, quantum butterflies... 

Closing as not reproducible.
