### ISSUE TITLE
[TC/TCCS: COO] Request Active COO be CC'd on report/match denials

### ISSUE THREAD

**Issue by TCTails** [emperorshammer/issues-incoming-queue#89]
Good evening/early morning Internet Office,
Is it possible to adjust the system so that if a member of Combat Operations (or TCCS if for some reason SOO/TCCOM was substituting for COO) denies a match, that the active Combat Operations Officer be CC'd on denials? It appears if I understand current setup, each individual contributor that denies the match gets the email report/notification but COO does not.

**Comment by turtlexiv** [comment]
Closing since emperorshammer/tiecorps#382 will cover this.
