### ISSUE TITLE
Suggestion: Show image of screenshot uploaded on submission page for QoL when inputing data

### ISSUE THREAD

**Issue by TheBlackxRanger** [emperorshammer/issues-incoming-queue#99]
Lazy, I know. But I think it would be helpful to show the screenshot uploaded on the submission page so that way you dont have to go back and forth between windows explorer/image viewer to input the data. 

Example below

![image](https://user-images.githubusercontent.com/74426625/167317233-206a8fc7-da4c-440a-9b5f-f82cbec87639.png)

**Comment by turtlexiv** [comment]
Thanks for the suggestion.

This is now implemented as of PR emperorshammer/tiecorps#533 .
